# Generated by Django 5.1.1 on 2024-09-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_element', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=255)),
                ('starting_page', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClickElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('text_input_elements', models.JSONField(blank=True, default=dict)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_elements', to='myapp.test')),
            ],
        ),
        migrations.CreateModel(
            name='Tooltip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('page', models.CharField(max_length=255)),
                ('target_element', models.CharField(max_length=255)),
                ('target_area_element', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('interactive_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooltips', to='myapp.interactiveguide')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='myapp.tutorial'),
        ),
    ]
