# Generated by Django 5.1.1 on 2024-09-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentation',
            new_name='DocumentationPages',
        ),
        migrations.RenameModel(
            old_name='Tooltip',
            new_name='TooltipInteractiveGuide',
        ),
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='TutorialStage',
        ),
        migrations.CreateModel(
            name='TooltipTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('page', models.CharField(max_length=255)),
                ('target_element', models.CharField(max_length=255)),
                ('target_area_element', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tutorial_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooltips', to='myapp.tutorialstage')),
            ],
        ),
    ]
