# Generated by Django 5.1.1 on 2024-09-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_documentationpages_documentationpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpicon',
            old_name='target_element',
            new_name='target_element_id',
        ),
        migrations.RenameField(
            model_name='interactiveguide',
            old_name='page',
            new_name='starting_page',
        ),
        migrations.RenameField(
            model_name='tooltipinteractiveguide',
            old_name='target_area_element',
            new_name='target_area_element_id',
        ),
        migrations.RenameField(
            model_name='tooltipinteractiveguide',
            old_name='target_element',
            new_name='target_element_id',
        ),
        migrations.RenameField(
            model_name='tooltiptutorial',
            old_name='target_area_element',
            new_name='target_area_element_id',
        ),
        migrations.RenameField(
            model_name='tooltiptutorial',
            old_name='target_element',
            new_name='target_element_id',
        ),
        migrations.RenameField(
            model_name='tutorialstage',
            old_name='stage_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='clickelement',
            name='text_input_elements',
        ),
        migrations.AlterField(
            model_name='tooltipinteractiveguide',
            name='type',
            field=models.CharField(choices=[('informative', 'Informative'), ('action', 'Action')], max_length=11),
        ),
        migrations.AlterField(
            model_name='tooltiptutorial',
            name='type',
            field=models.CharField(choices=[('informative', 'Informative'), ('action', 'Action')], max_length=11),
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_tasks', to='myapp.tutorialstage')),
            ],
        ),
        migrations.AlterField(
            model_name='clickelement',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_elements', to='myapp.testtask'),
        ),
        migrations.CreateModel(
            name='TextInputElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('required_input', models.TextField()),
                ('click_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_input_elements', to='myapp.clickelement')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
