# Generated by Django 5.1.1 on 2024-09-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_target_element_helpicon_target_element_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelpIcon',
            new_name='InfoIcon',
        ),
    ]
