# Generated by Django 5.1.1 on 2024-09-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_helpicon_infoicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickelement',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testtask',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tooltipinteractiveguide',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tooltiptutorial',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
