# Generated by Django 5.1.1 on 2024-09-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_clickelement_position_testtask_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickelement',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='testtask',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='tooltipinteractiveguide',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='tooltiptutorial',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='textinputelement',
            name='required_input',
            field=models.CharField(max_length=255),
        ),
    ]
